-- AlterTable
ALTER TABLE "User" ADD COLUMN     "sTSId" TEXT;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_sTSId_fkey" FOREIGN KEY ("sTSId") REFERENCES "STS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
